[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test configuration
test = "test"
cache_path = "cache_forge"
broadcast = "broadcast"
ffi = false
verbosity = 2

# Fuzzing
[fuzz]
runs = 1000
max_test_rejects = 5000
dictionary_weight = 40

# Invariants 
[invariant]
runs = 100
depth = 15
fail_on_revert = false

# CI profile
[profile.ci]
fuzz = { runs = 500 }
verbosity = 1 